version: '3'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    container_name: mysql-server
    networks:
      - mynetwork

  api:
    build: .
    container_name: api-container
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - redis
    networks:
      - mynetwork

  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: redis-container
    networks:
      - mynetwork

  worker:
    image: forum-tim103-api
    volumes:
      - .:/app
    depends_on:
      - redis
      - api
    command: rq worker --url redis://redis:6379
    environment:
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge