version: '3'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    container_name: mysql-server
    networks:
      - mynetwork

  api:
    build: .
    container_name: api-container
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5000:5000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge